### ISSUE TITLE
Started getting this on 14.04 today? tried reinstalling and such no luck was working great.

### ISSUE THREAD

**Issue by tdrone993** [cblument/spotternetwork#3]
python -mspotternetwork
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "build/bdist.linux-x86_64/egg/spotternetwork.py", line 118, in <module>
  File "build/bdist.linux-x86_64/egg/spotternetwork.py", line 54, in load_from_k                                                                                                                      ml
  File "/usr/local/lib/python2.7/dist-packages/pykml-0.1.0-py2.7.egg/pykml/parse                                                                                                                      r.py", line 55, in parse
    return objectify.parse(fileobject)
  File "src/lxml/lxml.objectify.pyx", line 1835, in lxml.objectify.parse (src/lx                                                                                                                      ml/lxml.objectify.c:25521)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.                                                                                                                      etree.c:79801)
  File "src/lxml/parser.pxi", line 1803, in lxml.etree._parseDocument (src/lxml/                                                                                                                      lxml.etree.c:116263)
  File "src/lxml/parser.pxi", line 1823, in lxml.etree._parseFilelikeDocument (s                                                                                                                      rc/lxml/lxml.etree.c:116555)
  File "src/lxml/parser.pxi", line 1718, in lxml.etree._parseDocFromFilelike (sr                                                                                                                      c/lxml/lxml.etree.c:115316)
  File "src/lxml/parser.pxi", line 1139, in lxml.etree._BaseParser._parseDocFrom                                                                                                                      Filelike (src/lxml/lxml.etree.c:110190)
  File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handlePars                                                                                                                      eResultDoc (src/lxml/lxml.etree.c:103404)
  File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lx                                                                                                                      ml/lxml.etree.c:105058)
  File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml                                                                                                                      /lxml.etree.c:103967)
lxml.etree.XMLSyntaxError: Entity 'eacute' not defined, line 1202, column 106

**Comment by cblument** [comment]
Did you install the dependencies for ubuntu referenced in the README?  I think you are missing them.

**Comment by tdrone993** [comment]
yes it was working then quit

**Comment by cblument** [comment]
Looks like an xml problem, http://stackoverflow.com/questions/2835077/lxml-unicode-entity-parse-problems

I think é is somewhere in the xml.  Will have to figure out a way around that
